language: generic 
sudo: required
services:
  -docker

before_install:
  - docker build -t tszchan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tszchan/docker-react npm run test -- --coverage